language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm run tsc
deploy:
  provider: npm
  email: l.gholoi@outlook.com
  api_key:
    secure: eci4zHhN8yhKSyzggivHwK4AYadgvQViM/dUsA9AK9vTeFqolALJY9SwBxp5z8ZD9A7kcRaNH1D1HQrUb2Te2Ywt2kdygkTuuD9qZM5RUEnwGbG0LJDJM1BVytD8Yu8yXHfSz2clVIRlR8xBkIcRJIm7TSv5QZOHqlm9tLK5wPOpbdkPFXxUIqTies/OY1x6Qq339LwFmZ07D7Y2kk0yCQrF5ff879PE4MJxRilYkQ6e3tV02gK1996Pis16xl7py+5p1q70SFZfcPGDHXPHAv1qXOm2uQoII5/RNZQy2VgXysRdjDH/U7A1H8rOJT1kEIXLqlUymuHH4uGq9w+8fdcpFXug3hiahLVsMMHmcDfgW4CK3VIbq0bq7GVX1C2RSilVDO/LpNavLfE+hzwINgMEIYt2V9q6iOcdGxtC05qmnX28v3GTA924KaHpJgLP/VO71LAgiiH4tIMpL0Op+Ghrelfh2J7JJj/brCfN+DS9CZcHLFDyewUxpdUivdkdGxpXuLGSjntVlDJK13YW2T3TOMMVflv+GrZne6rsRZJRoKCk+d8ZNwmF4LlDFAd5D/+5IJX2XShSfdSFWv9NublJnloc25KcVv1e1Wi/GCCSE0K4nWWMCwSfyklCqx7WchCHlf5KnmBOGYVp5N3Ef+WJ0wS/6QdVeUx7PHv/KbY=
  on:
    tags: true
    branch: master
  skip_cleanup: true
